spring:
  jpa:
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
---
spring:
  profiles: mysql
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental
    username: root
    password: root
pool-size: 100

